#!/bin/bash

#####################
# Start GNOME Keyring
#####################
#eval `dbus-launch --sh-syntax --exit-with-session`
eval $(/usr/bin/gnome-keyring-daemon)
dbus-update-activation-environment --systemd DISPLAY
#eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO

#####################
# Background daemons
#####################
start-pulseaudio-x11
xset s off b off r rate 300 30 
nitrogen --restore

#####################
# Delay startup
#####################
(sleep 0.5 && 
    compton --xrender-sync-fence& 
    nm-applet& 
    ~/bin/lowram.sh&
    ~/bin/batestim.sh&
#    ~/bin/pokemon.sh&
    ~/bin/kl.sh&
    urxvtd&
    unclutter -root&
    redshift-gtk&
    synclient MaxSpeed=2.5 AccelFactor=0.3
)&

#####################
# POuL widget updater
#####################
#~/bin/poul_wm >/dev/null 2>&1 & 

#####################
# Last things
#####################
xrdb ~/.Xresources
setxkbmap us altgr-intl
xsetroot -cursor_name left_ptr
xautolock -time 5 -locker /home/al/bin/lock -nowlocker /home/al/bin/lock&
chmod o+x /run/user/1000/pulse
chmod o+x /run/user/1000
export ANDROID_HOME=/opt/android-sdk-linux

#####################
# Start the Window Manager
#####################
exec awesome
